---
:api_key: ee9c885f2e4a2ecec5ff4ba0029a60c7
:password: 59b9ee16ce378f000d21d19dfc5bf0ab
:store: urban-zen-foundation.myshopify.com
:theme_id: 
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
